import React from "react";
import Head from "next/head";
import { styled } from "@mui/material";
import { useRouter } from "next/router";
import client from "@/utils/apollo-client";
import GET_ALL_POKEMONS from "@/queries/getAllPokemons";
import Pokemons from "../components/Pokemons";
import { PokemonPage } from "@/@types/types";

const StyledDiv = styled("div")(
	(props) => `
    display: flex;
    max-width: 1280px;
    margin: auto;
    height: 100%;
    background-color: red;
`
);

type PageType = {
	data?: PokemonPage;
	error?: {
		message?: string;
	};
	loading?: boolean;
};
const PageValues = (props: PageType) => {
	const router = useRouter();
	const { id } = router.query;

	const { data } = props;

	if (router.isFallback) {
		return <>Loading...</>;
	}
	return (
		<>
			<Head>
				<title>Pokedex - Buyceps</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/logo.svg" />
			</Head>
			<main>
				<Pokemons data={data} page={id?.toString()} />
			</main>
		</>
	);
};

export default PageValues;

export async function getStaticProps(context: { params: { id: string } }) {
	const { params } = context;
	// Getting all pokemon list from GraphQL API
	const { data } = await client.query({
		query: GET_ALL_POKEMONS,
		variables: {
			first: parseInt(params.id) * 20,
		},
	});

	return {
		props: {
			data: { ...data, pokemons: [...data.pokemons.slice(-20)] },
		},
	};
}

export async function getStaticPaths() {
	return {
		paths: [
			{
				params: { id: "1" },
			},
			{
				params: { id: "2" },
			},
			{
				params: { id: "3" },
			},
		],
		fallback: true,
	};
}
