import Head from "next/head";
import Image from "next/image";

// import styles from "@/styles/Home.module.css";
import Pokemons from "../components/Pokemons";
import client from "@/utils/apollo-client";
import GET_ALL_POKEMONS from "@/queries/getAllPokemons";
import { PokemonPage } from "@/@types/types";
import PageHandler from "../components/PageHandler";

export default function Home({ data }: { data: PokemonPage }) {
	return (
		<>
			<Head>
				<title>Pokedex - Buyceps</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/logo.svg" />
			</Head>
			<main>
				<Pokemons data={data} />
			</main>
		</>
	);
}

export async function getStaticProps() {
	// Get external data from the file system, API, DB, etc.
	const { data } = await client.query({
		query: GET_ALL_POKEMONS,
		variables: {
			first: 20,
		},
	});

	// The value of the `props` key will be
	//  passed to the `Home` component
	return {
		props: {
			data,
		},
	};
}
